language: node_js
node_js:
- '8'
before_install:
  - chmod +x scripts/push.sh
install:
- npm install
script: npm run check
deploy:
  provider: script
  script: scripts/push.sh
  on:
    branch: master